### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by wakudrle** [mikelovely/adr-framework#1]
When I do a git clone (Ubuntu 18.04) and then a composer install, I get the following warning. 

`Deprecation warning: Your package name Action Domain Responder is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.`

**Comment by mikelovely** [comment]
@wakudrle https://github.com/mikelovely/adr-framework/pull/2 Fixed. Thanks!
